services:
  #apppostgres:
  #  image: postgres
  #  restart: always
  #  environment:
  #    - POSTGRES_USER=root
  #    - POSTGRES_PASSWORD=root
  #    - POSTGRES_DB=ymdb
  #  volumes:
  #    - ./Volumes/Data/Db:/var/lib/postgresql/data
  #  ports:
  #    - 5432:5432
        
  app:
    # image: app-bot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./Db:/app/Db:rw
    #depends_on:
    #  - apppostgres