// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YourMatchTgBot;

#nullable disable

namespace YourMatchTgBot.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240306140012_CitiesNotNullProperties")]
    partial class CitiesNotNullProperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.1.24081.2");

            modelBuilder.Entity("InterestUser", b =>
                {
                    b.Property<int>("InterestsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UsersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InterestsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("InterestUser");
                });

            modelBuilder.Entity("YourMatchTgBot.Models.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("YourMatchTgBot.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "📚"
                        },
                        new
                        {
                            Id = 2,
                            Name = "🎲"
                        },
                        new
                        {
                            Id = 4,
                            Name = "🚶"
                        },
                        new
                        {
                            Id = 8,
                            Name = "💃"
                        },
                        new
                        {
                            Id = 16,
                            Name = "🎞"
                        },
                        new
                        {
                            Id = 32,
                            Name = "🏅"
                        },
                        new
                        {
                            Id = 64,
                            Name = "💻"
                        },
                        new
                        {
                            Id = 128,
                            Name = "🚙"
                        },
                        new
                        {
                            Id = 256,
                            Name = "🏔"
                        },
                        new
                        {
                            Id = 512,
                            Name = "🍲"
                        },
                        new
                        {
                            Id = 1024,
                            Name = "🎧"
                        },
                        new
                        {
                            Id = 2048,
                            Name = "🍳"
                        },
                        new
                        {
                            Id = 4096,
                            Name = "🛍"
                        });
                });

            modelBuilder.Entity("YourMatchTgBot.Models.TempInterest", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("TempInterest");
                });

            modelBuilder.Entity("YourMatchTgBot.Models.TempUserMedia", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaFileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "MediaFileId");

                    b.ToTable("TempUserMedia");
                });

            modelBuilder.Entity("YourMatchTgBot.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<short?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Education")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterestsFlags")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PartnerGender")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TemporaryInterestsFlags")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZodiacSign")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("YourMatchTgBot.Models.UserMedia", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaFileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "MediaFileId");

                    b.ToTable("UserMedia");
                });

            modelBuilder.Entity("InterestUser", b =>
                {
                    b.HasOne("YourMatchTgBot.Models.Interest", null)
                        .WithMany()
                        .HasForeignKey("InterestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YourMatchTgBot.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YourMatchTgBot.Models.TempInterest", b =>
                {
                    b.HasOne("YourMatchTgBot.Models.Interest", "Interest")
                        .WithMany()
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YourMatchTgBot.Models.User", "User")
                        .WithMany("TemporaryInterests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YourMatchTgBot.Models.TempUserMedia", b =>
                {
                    b.HasOne("YourMatchTgBot.Models.User", null)
                        .WithMany("TemporaryPhotos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YourMatchTgBot.Models.User", b =>
                {
                    b.HasOne("YourMatchTgBot.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.Navigation("City");
                });

            modelBuilder.Entity("YourMatchTgBot.Models.UserMedia", b =>
                {
                    b.HasOne("YourMatchTgBot.Models.User", null)
                        .WithMany("Photos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YourMatchTgBot.Models.User", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("TemporaryInterests");

                    b.Navigation("TemporaryPhotos");
                });
#pragma warning restore 612, 618
        }
    }
}
