// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YourMatchTgBot;

#nullable disable

namespace YourMatchTgBot.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.1.24081.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YourMatchTgBot.Models.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Belgorod"
                        });
                });

            modelBuilder.Entity("YourMatchTgBot.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "📚"
                        },
                        new
                        {
                            Id = 2,
                            Name = "🎲"
                        },
                        new
                        {
                            Id = 3,
                            Name = "🚶"
                        },
                        new
                        {
                            Id = 4,
                            Name = "💃"
                        },
                        new
                        {
                            Id = 5,
                            Name = "🎞"
                        },
                        new
                        {
                            Id = 6,
                            Name = "🏅"
                        },
                        new
                        {
                            Id = 7,
                            Name = "💻"
                        },
                        new
                        {
                            Id = 8,
                            Name = "🚙"
                        },
                        new
                        {
                            Id = 9,
                            Name = "🏔"
                        },
                        new
                        {
                            Id = 10,
                            Name = "🍲"
                        },
                        new
                        {
                            Id = 11,
                            Name = "🎧"
                        },
                        new
                        {
                            Id = 12,
                            Name = "🍳"
                        },
                        new
                        {
                            Id = 13,
                            Name = "🛍"
                        });
                });

            modelBuilder.Entity("YourMatchTgBot.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short?>("Age")
                        .HasColumnType("smallint");

                    b.Property<long?>("CityId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Education")
                        .HasColumnType("text");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("PartnerGender")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("ZodiacSign")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("YourMatchTgBot.Models.UserPhoto", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("PhotoFileId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "PhotoFileId");

                    b.ToTable("UserPhoto");
                });

            modelBuilder.Entity("YourMatchTgBot.Models.Interest", b =>
                {
                    b.HasOne("YourMatchTgBot.Models.User", null)
                        .WithMany("Interests")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("YourMatchTgBot.Models.User", b =>
                {
                    b.HasOne("YourMatchTgBot.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.Navigation("City");
                });

            modelBuilder.Entity("YourMatchTgBot.Models.UserPhoto", b =>
                {
                    b.HasOne("YourMatchTgBot.Models.User", null)
                        .WithMany("Photos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YourMatchTgBot.Models.User", b =>
                {
                    b.Navigation("Interests");

                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
