// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YourMatchTgBot;

#nullable disable

namespace YourMatchTgBot.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.1.24081.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("InterestUser", b =>
                {
                    b.Property<int>("InterestsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UsersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InterestsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("InterestUser");
                });

            modelBuilder.Entity("YourMatchTgBot.Models.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedDisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 150993485L,
                            DisplayName = "Saint Petersburg, Northwestern Federal District, Russia",
                            Name = "Saint Petersburg",
                            TranslatedDisplayName = "Санкт-Петербург, Северо-Западный федеральный округ, Россия",
                            TranslatedName = "Санкт-Петербург"
                        },
                        new
                        {
                            Id = 171488446L,
                            DisplayName = "Belgorod, Belgorodsky District, Belgorod Oblast, Central Federal District, Russia",
                            Name = "Belgorod",
                            TranslatedDisplayName = "Белгород, Белгородский район, Белгородская область, Центральный федеральный округ, Россия",
                            TranslatedName = "Белгород"
                        },
                        new
                        {
                            Id = 170978781L,
                            DisplayName = "Kursk, Kursk Oblast, Central Federal District, 305000, Russia",
                            Name = "Kursk",
                            TranslatedDisplayName = "Курск, Курская область, Центральный федеральный округ, 305000, Россия",
                            TranslatedName = "Курск"
                        },
                        new
                        {
                            Id = 172182020L,
                            DisplayName = "Voronezh, Voronezh Oblast, Central Federal District, Russia",
                            Name = "Voronezh",
                            TranslatedDisplayName = "Воронеж, Воронежская область, Центральный федеральный округ, Россия",
                            TranslatedName = "Воронеж"
                        },
                        new
                        {
                            Id = 172497247L,
                            DisplayName = "Penza, Penza Oblast, Volga Federal District, Russia",
                            Name = "Penza",
                            TranslatedDisplayName = "Пенза, Пензенская область, Приволжский федеральный округ, Россия",
                            TranslatedName = "Пенза"
                        },
                        new
                        {
                            Id = 174159235L,
                            DisplayName = "Bryansk, Bryansk Oblast, Central Federal District, Russia",
                            Name = "Bryansk",
                            TranslatedDisplayName = "Брянск, Брянская область, Центральный федеральный округ, Россия",
                            TranslatedName = "Брянск"
                        },
                        new
                        {
                            Id = 177211127L,
                            DisplayName = "Izhevsk, Udmurtia, Volga Federal District, Russia",
                            Name = "Izhevsk",
                            TranslatedDisplayName = "Ижевск, Удмуртия, Приволжский федеральный округ, Россия",
                            TranslatedName = "Ижевск"
                        },
                        new
                        {
                            Id = 179737040L,
                            DisplayName = "Samara, Samara Oblast, Volga Federal District, 443028, Russia",
                            Name = "Samara",
                            TranslatedDisplayName = "Самара, Самарская область, Приволжский федеральный округ, 443028, Россия",
                            TranslatedName = "Самара"
                        },
                        new
                        {
                            Id = 174706474L,
                            DisplayName = "Moscow, Central Federal District, Russia",
                            Name = "Moscow",
                            TranslatedDisplayName = "Москва, Центральный федеральный округ, Россия",
                            TranslatedName = "Москва"
                        });
                });

            modelBuilder.Entity("YourMatchTgBot.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "📚"
                        },
                        new
                        {
                            Id = 2,
                            Name = "🎲"
                        },
                        new
                        {
                            Id = 4,
                            Name = "🚶"
                        },
                        new
                        {
                            Id = 8,
                            Name = "💃"
                        },
                        new
                        {
                            Id = 16,
                            Name = "🎞"
                        },
                        new
                        {
                            Id = 32,
                            Name = "🏅"
                        },
                        new
                        {
                            Id = 64,
                            Name = "💻"
                        },
                        new
                        {
                            Id = 128,
                            Name = "🚙"
                        },
                        new
                        {
                            Id = 256,
                            Name = "🏔"
                        },
                        new
                        {
                            Id = 512,
                            Name = "🍲"
                        },
                        new
                        {
                            Id = 1024,
                            Name = "🎧"
                        },
                        new
                        {
                            Id = 2048,
                            Name = "🍳"
                        },
                        new
                        {
                            Id = 4096,
                            Name = "🛍"
                        });
                });

            modelBuilder.Entity("YourMatchTgBot.Models.TempInterest", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("TempInterest");
                });

            modelBuilder.Entity("YourMatchTgBot.Models.TempUserMedia", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaFileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "MediaFileId");

                    b.ToTable("TempUserMedia");
                });

            modelBuilder.Entity("YourMatchTgBot.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<short?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentOffset")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Education")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterestsFlags")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PartnerGender")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SearchOffset")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TemporaryInterestsFlags")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZodiacSign")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            Age = (short)19,
                            CityId = 172182020L,
                            CurrentOffset = 0,
                            Description = "﻿В конце жизни важны не прожитые годы, а то, как вы их прожили.",
                            Gender = 2,
                            Height = 140,
                            InterestsFlags = 208,
                            Latitude = 51.660598200000003,
                            Longitude = 39.200585799999999,
                            Name = "Жданова Маргарита Юрьевна",
                            PartnerGender = 3,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -2L,
                            Age = (short)16,
                            CityId = 172497247L,
                            CurrentOffset = 0,
                            Description = "﻿Окружай себя только теми людьми, кто будет тянуть тебя выше. Просто жизнь уже полна теми, кто хочет тянуть тебя вниз",
                            Gender = 1,
                            Height = 141,
                            InterestsFlags = 1072,
                            Latitude = 53.193783600000003,
                            Longitude = 45.006741250609664,
                            Name = "Фролов Евгений Дмитриевич",
                            PartnerGender = 3,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -3L,
                            Age = (short)27,
                            CityId = 170978781L,
                            CurrentOffset = 0,
                            Description = "﻿Каждый день не может быть хорошим, важно лишь запомнить хорошее в каждом дне",
                            Gender = 1,
                            Height = 142,
                            InterestsFlags = 104,
                            Latitude = 51.727035649999998,
                            Longitude = 36.192247956921115,
                            Name = "Харитонов Александр Александрович",
                            PartnerGender = 1,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -4L,
                            Age = (short)38,
                            CityId = 174159235L,
                            CurrentOffset = 0,
                            Description = "﻿Грамм собственного опыта стоит дороже тонны чужих наставлений!",
                            Gender = 1,
                            Height = 143,
                            InterestsFlags = 1538,
                            Latitude = 53.2423778,
                            Longitude = 34.3668288,
                            Name = "Сафонов Иван Даниилович",
                            PartnerGender = 2,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -5L,
                            Age = (short)33,
                            CityId = 172182020L,
                            CurrentOffset = 0,
                            Description = "﻿Можно всё время дурачить некоторых, можно некоторое время дурачить всех, но нельзя все время дурачить всех.",
                            Gender = 2,
                            Height = 144,
                            InterestsFlags = 592,
                            Latitude = 51.660598200000003,
                            Longitude = 39.200585799999999,
                            Name = "Горшкова Варвара Антоновна",
                            PartnerGender = 1,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -6L,
                            Age = (short)17,
                            CityId = 177211127L,
                            CurrentOffset = 0,
                            Description = "﻿Нельзя сдаваться не только после одного, но и после ста поражений.",
                            Gender = 2,
                            Height = 145,
                            InterestsFlags = 1057,
                            Latitude = 56.860517450000003,
                            Longitude = 53.197730742455306,
                            Name = "Костина Ксения Степановна",
                            PartnerGender = 1,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -7L,
                            Age = (short)20,
                            CityId = 179737040L,
                            CurrentOffset = 0,
                            Description = "﻿Характер подобен дереву, а репутация — его тени. Мы заботимся о тени, но на самом деле надо думать о дереве.",
                            Gender = 2,
                            Height = 146,
                            InterestsFlags = 49,
                            Latitude = 53.198627000000002,
                            Longitude = 50.113987000000002,
                            Name = "Исаева Полина Максимовна",
                            PartnerGender = 2,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -8L,
                            Age = (short)32,
                            CityId = 174706474L,
                            CurrentOffset = 0,
                            Description = "﻿Удвоенное желание есть страсть, удвоенная страсть становится безумием.",
                            Gender = 2,
                            Height = 147,
                            InterestsFlags = 81,
                            Latitude = 55.750541200000001,
                            Longitude = 37.617478200000001,
                            Name = "Гончарова Ника Артёмовна",
                            PartnerGender = 3,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -9L,
                            Age = (short)35,
                            CityId = 170978781L,
                            CurrentOffset = 0,
                            Description = "﻿Когда мне тяжело, я всегда напоминаю себе о том, что если я сдамся — лучше не станет",
                            Gender = 1,
                            Height = 148,
                            InterestsFlags = 1042,
                            Latitude = 51.727035649999998,
                            Longitude = 36.192247956921115,
                            Name = "Трифонов Макар Янович",
                            PartnerGender = 2,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -10L,
                            Age = (short)17,
                            CityId = 174159235L,
                            CurrentOffset = 0,
                            Description = "﻿Чтобы вы ни делали, делайте это хорошо",
                            Gender = 1,
                            Height = 149,
                            InterestsFlags = 3073,
                            Latitude = 53.2423778,
                            Longitude = 34.3668288,
                            Name = "Рудаков Артём Артёмович",
                            PartnerGender = 3,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -11L,
                            Age = (short)19,
                            CityId = 172497247L,
                            CurrentOffset = 0,
                            Description = "﻿Единственное правило в жизни, по которому нужно жить — оставаться человеком в любых ситуациях",
                            Gender = 1,
                            Height = 150,
                            InterestsFlags = 672,
                            Latitude = 53.193783600000003,
                            Longitude = 45.006741250609664,
                            Name = "Новиков Роман Андреевич",
                            PartnerGender = 1,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -12L,
                            Age = (short)36,
                            CityId = 177211127L,
                            CurrentOffset = 0,
                            Description = "﻿Быстрее всего учишься в трех случаях — до 7 лет, на тренингах, и когда жизнь загнала тебя в угол",
                            Gender = 1,
                            Height = 151,
                            InterestsFlags = 50,
                            Latitude = 56.860517450000003,
                            Longitude = 53.197730742455306,
                            Name = "Иванов Ярослав Артёмович",
                            PartnerGender = 2,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -13L,
                            Age = (short)16,
                            CityId = 179737040L,
                            CurrentOffset = 0,
                            Description = "﻿Живи так — чтобы люди, столкнувшись с тобой, улыбнулись, а, общаясь с тобой, стали чуточку счастливее",
                            Gender = 1,
                            Height = 152,
                            InterestsFlags = 1284,
                            Latitude = 53.198627000000002,
                            Longitude = 50.113987000000002,
                            Name = "Мальцев Артём",
                            PartnerGender = 3,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -14L,
                            Age = (short)25,
                            CityId = 174706474L,
                            CurrentOffset = 0,
                            Description = "﻿Кто хочет жить для других, не должен пренебрегать собственной жизнью",
                            Gender = 1,
                            Height = 153,
                            InterestsFlags = 2177,
                            Latitude = 55.750541200000001,
                            Longitude = 37.617478200000001,
                            Name = "Медведев Иван",
                            PartnerGender = 1,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -15L,
                            Age = (short)33,
                            CityId = 150993485L,
                            CurrentOffset = 0,
                            Description = "﻿Жизнь — не зебра из черных и белых полос, а шахматная доска. Здесь все зависит от твоего хода",
                            Gender = 1,
                            Height = 154,
                            InterestsFlags = 296,
                            Latitude = 59.938732000000002,
                            Longitude = 30.316229,
                            Name = "Кузнецов Серафим",
                            PartnerGender = 1,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -16L,
                            Age = (short)17,
                            CityId = 171488446L,
                            CurrentOffset = 0,
                            Description = "﻿Красота — это внешность, фото — искусство, а главное в жизни — доброе сердце, характер и чувства",
                            Gender = 1,
                            Height = 155,
                            InterestsFlags = 2120,
                            Latitude = 50.5955595,
                            Longitude = 36.587339399999998,
                            Name = "Степанов Валерий",
                            PartnerGender = 2,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -17L,
                            Age = (short)34,
                            CityId = 179737040L,
                            CurrentOffset = 0,
                            Description = "﻿Стремитесь не к тому, чтобы добиться успеха, а к тому, чтобы твоя жизнь имела смысл",
                            Gender = 2,
                            Height = 156,
                            InterestsFlags = 642,
                            Latitude = 53.198627000000002,
                            Longitude = 50.113987000000002,
                            Name = "Вешнякова Валерия Яковлевна",
                            PartnerGender = 3,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -18L,
                            Age = (short)16,
                            CityId = 174706474L,
                            CurrentOffset = 0,
                            Description = "﻿Жизнь измеряется не числом вдохов и выдохов, а числом мгновений, в которые перехватывает дыхание.",
                            Gender = 2,
                            Height = 157,
                            InterestsFlags = 69,
                            Latitude = 55.750541200000001,
                            Longitude = 37.617478200000001,
                            Name = "Федорова Софья Егоровна",
                            PartnerGender = 1,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -19L,
                            Age = (short)25,
                            CityId = 150993485L,
                            CurrentOffset = 0,
                            Description = "Я понял, что жизнь ничего не стоит, но я также понял, что ничто не стоит жизни.",
                            Gender = 2,
                            Height = 158,
                            InterestsFlags = 259,
                            Latitude = 59.938732000000002,
                            Longitude = 30.316229,
                            Name = "Михеева Аиша Михайловна",
                            PartnerGender = 2,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -20L,
                            Age = (short)30,
                            CityId = 171488446L,
                            CurrentOffset = 0,
                            Description = "﻿Мы не всегда свободны от ошибок, по поводу которых смеемся над другими.",
                            Gender = 2,
                            Height = 159,
                            InterestsFlags = 2113,
                            Latitude = 50.5955595,
                            Longitude = 36.587339399999998,
                            Name = "Троицкая Мария Артёмовна",
                            PartnerGender = 3,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -21L,
                            Age = (short)16,
                            CityId = 171488446L,
                            CurrentOffset = 0,
                            Description = "Хороший инвестор — всё равно что прилежный студент. Каждый день я трачу часы на чтение финансовой прессы.",
                            Gender = 2,
                            Height = 160,
                            InterestsFlags = 1544,
                            Latitude = 50.5955595,
                            Longitude = 36.587339399999998,
                            Name = "Макарова Валерия Макаровна",
                            PartnerGender = 1,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -22L,
                            Age = (short)21,
                            CityId = 170978781L,
                            CurrentOffset = 0,
                            Description = "﻿Современная музыка хороша уже тем, что, если ты ошибешься, никто не заметит.",
                            Gender = 2,
                            Height = 161,
                            InterestsFlags = 74,
                            Latitude = 51.727035649999998,
                            Longitude = 36.192247956921115,
                            Name = "Куликова Виктория",
                            PartnerGender = 2,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -23L,
                            Age = (short)31,
                            CityId = 174159235L,
                            CurrentOffset = 0,
                            Description = "﻿Музыканты рисуют свои картины на фоне тишины. Мы даем музыку, а вы даете тишину.",
                            Gender = 2,
                            Height = 162,
                            InterestsFlags = 38,
                            Latitude = 53.2423778,
                            Longitude = 34.3668288,
                            Name = "Лукьянова Анастасия",
                            PartnerGender = 3,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -24L,
                            Age = (short)17,
                            CityId = 172497247L,
                            CurrentOffset = 0,
                            Description = "﻿Если все сложилось не так, как вы ожидали, не расстраивайтесь. Божьи планы всегда лучше наших",
                            Gender = 2,
                            Height = 163,
                            InterestsFlags = 1664,
                            Latitude = 53.193783600000003,
                            Longitude = 45.006741250609664,
                            Name = "Киселева Варвара",
                            PartnerGender = 1,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -25L,
                            Age = (short)24,
                            CityId = 177211127L,
                            CurrentOffset = 0,
                            Description = "﻿Никогда не осуждайте человека, пока не пройдете долгий путь в его ботинках",
                            Gender = 2,
                            Height = 164,
                            InterestsFlags = 280,
                            Latitude = 56.860517450000003,
                            Longitude = 53.197730742455306,
                            Name = "Зайцева Валерия",
                            PartnerGender = 2,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -26L,
                            Age = (short)37,
                            CityId = 171488446L,
                            CurrentOffset = 0,
                            Description = "﻿О нравственных качествах человека нужно судить не по отдельным его усилиям, а по его повседневной жизни",
                            Gender = 1,
                            Height = 165,
                            InterestsFlags = 392,
                            Latitude = 50.5955595,
                            Longitude = 36.587339399999998,
                            Name = "Григорьев Гордей",
                            PartnerGender = 1,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -27L,
                            Age = (short)16,
                            CityId = 172182020L,
                            CurrentOffset = 0,
                            Description = "﻿Никто не изготовит замок без ключа, также и жизнь не даст проблемы без решения",
                            Gender = 1,
                            Height = 166,
                            InterestsFlags = 2192,
                            Latitude = 51.660598200000003,
                            Longitude = 39.200585799999999,
                            Name = "Иванов Илья",
                            PartnerGender = 2,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -28L,
                            Age = (short)16,
                            CityId = 170978781L,
                            CurrentOffset = 0,
                            Description = "﻿Нужно не тратить время, а инвестировать в него",
                            Gender = 1,
                            Height = 167,
                            InterestsFlags = 1600,
                            Latitude = 51.727035649999998,
                            Longitude = 36.192247956921115,
                            Name = "Лукьянов Александр",
                            PartnerGender = 3,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -29L,
                            Age = (short)28,
                            CityId = 174159235L,
                            CurrentOffset = 0,
                            Description = "﻿Перемены, происходящие в нашей жизни, есть следствие нашего выбора и наших решений",
                            Gender = 1,
                            Height = 168,
                            InterestsFlags = 1057,
                            Latitude = 53.2423778,
                            Longitude = 34.3668288,
                            Name = "Илья",
                            PartnerGender = 1,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -30L,
                            Age = (short)31,
                            CityId = 172497247L,
                            CurrentOffset = 0,
                            Description = "﻿Подлинным зеркалом нашего образа мыслей является наша жизнь",
                            Gender = 1,
                            Height = 169,
                            InterestsFlags = 1092,
                            Latitude = 53.193783600000003,
                            Longitude = 45.006741250609664,
                            Name = "Кирилл",
                            PartnerGender = 1,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -31L,
                            Age = (short)16,
                            CityId = 177211127L,
                            CurrentOffset = 0,
                            Description = "﻿Кто не стучится — тому не открывают. Кто не пробует — у того не получается",
                            Gender = 1,
                            Height = 170,
                            InterestsFlags = 5276,
                            Latitude = 56.860517450000003,
                            Longitude = 53.197730742455306,
                            Name = "Фёдор",
                            PartnerGender = 2,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -32L,
                            Age = (short)24,
                            CityId = 179737040L,
                            CurrentOffset = 0,
                            Description = "﻿Нынешняя молодежь так быстро взрослеет, что сознательно затягивает стадию инфантилизма.",
                            Gender = 1,
                            Height = 171,
                            InterestsFlags = 146,
                            Latitude = 53.198627000000002,
                            Longitude = 50.113987000000002,
                            Name = "Александр",
                            PartnerGender = 3,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -33L,
                            Age = (short)37,
                            CityId = 174706474L,
                            CurrentOffset = 0,
                            Description = "﻿Жить — значит меняться, меняться — значит взрослеть, а взрослеть — значит непрестанно творить себя самого.",
                            Gender = 1,
                            Height = 172,
                            InterestsFlags = 134,
                            Latitude = 55.750541200000001,
                            Longitude = 37.617478200000001,
                            Name = "Дмитрий",
                            PartnerGender = 1,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -34L,
                            Age = (short)17,
                            CityId = 150993485L,
                            CurrentOffset = 0,
                            Description = "﻿Как все великие путешественники, я видел больше, чем помню, и помню больше, чем видел.",
                            Gender = 1,
                            Height = 173,
                            InterestsFlags = 1034,
                            Latitude = 59.938732000000002,
                            Longitude = 30.316229,
                            Name = "Артемий",
                            PartnerGender = 2,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -35L,
                            Age = (short)19,
                            CityId = 171488446L,
                            CurrentOffset = 0,
                            Description = "﻿Добрые поступки не выходят за ворота; дурные — путешествуют на тысячу ри.",
                            Gender = 1,
                            Height = 174,
                            InterestsFlags = 100,
                            Latitude = 50.5955595,
                            Longitude = 36.587339399999998,
                            Name = "Денис",
                            PartnerGender = 3,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -36L,
                            Age = (short)24,
                            CityId = 172497247L,
                            CurrentOffset = 0,
                            Description = "Пессимист видит трудности при каждой возможности; оптимист в каждой трудности видит возможности",
                            Gender = 2,
                            Height = 175,
                            InterestsFlags = 1048,
                            Latitude = 53.193783600000003,
                            Longitude = 45.006741250609664,
                            Name = "Евсеева Александра",
                            PartnerGender = 2,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -37L,
                            Age = (short)38,
                            CityId = 177211127L,
                            CurrentOffset = 0,
                            Description = "﻿Не тот велик, кто никогда не падал, а тот велик — кто падал и вставал!",
                            Gender = 2,
                            Height = 176,
                            InterestsFlags = 1544,
                            Latitude = 56.860517450000003,
                            Longitude = 53.197730742455306,
                            Name = "Ершова Арина",
                            PartnerGender = 3,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -38L,
                            Age = (short)17,
                            CityId = 179737040L,
                            CurrentOffset = 0,
                            Description = "﻿В жизни нет безвыходных ситуаций, есть только непринятые решения",
                            Gender = 2,
                            Height = 177,
                            InterestsFlags = 52,
                            Latitude = 53.198627000000002,
                            Longitude = 50.113987000000002,
                            Name = "Сафонова Ксения",
                            PartnerGender = 1,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -39L,
                            Age = (short)21,
                            CityId = 174706474L,
                            CurrentOffset = 0,
                            Description = "﻿Никогда не делает ошибок в жизни только тот, кто не пробует ничего нового",
                            Gender = 2,
                            Height = 178,
                            InterestsFlags = 2208,
                            Latitude = 55.750541200000001,
                            Longitude = 37.617478200000001,
                            Name = "Комарова Эмилия",
                            PartnerGender = 1,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -40L,
                            Age = (short)33,
                            CityId = 150993485L,
                            CurrentOffset = 0,
                            Description = "﻿Не жалуйся на жизнь — кто-то мечтает о такой жизни, какой ты живешь",
                            Gender = 2,
                            Height = 179,
                            InterestsFlags = 336,
                            Latitude = 59.938732000000002,
                            Longitude = 30.316229,
                            Name = "Коновалова Вера",
                            PartnerGender = 2,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -41L,
                            Age = (short)16,
                            CityId = 171488446L,
                            CurrentOffset = 0,
                            Description = "﻿Если вы хотите, чтобы жизнь улыбалась вам, подарите ей сначала свое хорошее настроение",
                            Gender = 2,
                            Height = 180,
                            InterestsFlags = 296,
                            Latitude = 50.5955595,
                            Longitude = 36.587339399999998,
                            Name = "Петрова Алёна",
                            PartnerGender = 3,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -42L,
                            Age = (short)21,
                            CityId = 171488446L,
                            CurrentOffset = 0,
                            Description = "﻿Удивительно, как много у нас друзей, пока не понадобится хотя бы один.",
                            Gender = 2,
                            Height = 181,
                            InterestsFlags = 161,
                            Latitude = 50.5955595,
                            Longitude = 36.587339399999998,
                            Name = "Вера",
                            PartnerGender = 1,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -43L,
                            Age = (short)38,
                            CityId = 172182020L,
                            CurrentOffset = 0,
                            Description = "﻿Если это кофе, пожалуйста, принесите мне чаю, а если это чай, пожалуйста, принесите мне кофе.",
                            Gender = 2,
                            Height = 182,
                            InterestsFlags = 530,
                            Latitude = 51.660598200000003,
                            Longitude = 39.200585799999999,
                            Name = "Алиса",
                            PartnerGender = 2,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -44L,
                            Age = (short)16,
                            CityId = 170978781L,
                            CurrentOffset = 0,
                            Description = "﻿Нет такого желания, которого нельзя было бы загадагь.",
                            Gender = 2,
                            Height = 183,
                            InterestsFlags = 776,
                            Latitude = 51.727035649999998,
                            Longitude = 36.192247956921115,
                            Name = "Анастасия",
                            PartnerGender = 3,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -45L,
                            Age = (short)17,
                            CityId = 174159235L,
                            CurrentOffset = 0,
                            Description = "Человек всегда делает лишь то, что хочет, и делает это все-таки по необходимости.",
                            Gender = 2,
                            Height = 184,
                            InterestsFlags = 1408,
                            Latitude = 53.2423778,
                            Longitude = 34.3668288,
                            Name = "Олеся",
                            PartnerGender = 1,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -46L,
                            Age = (short)28,
                            CityId = 150993485L,
                            CurrentOffset = 0,
                            Description = "﻿Лучшее путешествие — то, которое не имеет завершения.",
                            Gender = 1,
                            Height = 185,
                            InterestsFlags = 26,
                            Latitude = 59.938732000000002,
                            Longitude = 30.316229,
                            Name = "Иван",
                            PartnerGender = 3,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -47L,
                            Age = (short)35,
                            CityId = 171488446L,
                            CurrentOffset = 0,
                            Description = "﻿Чем позже ты поедешь в Париж, тем старше и достопримечательнее будет собор Парижской Богоматери.",
                            Gender = 1,
                            Height = 186,
                            InterestsFlags = 328,
                            Latitude = 50.5955595,
                            Longitude = 36.587339399999998,
                            Name = "Максим",
                            PartnerGender = 1,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -48L,
                            Age = (short)17,
                            CityId = 171488446L,
                            CurrentOffset = 0,
                            Description = "﻿Я путешествую не для того, чтобы приехать куда-то, но чтобы ехать. Главное — это движение.",
                            Gender = 1,
                            Height = 187,
                            InterestsFlags = 584,
                            Latitude = 50.5955595,
                            Longitude = 36.587339399999998,
                            Name = "Arnyack",
                            PartnerGender = 1,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -49L,
                            Age = (short)23,
                            CityId = 172182020L,
                            CurrentOffset = 0,
                            Description = "﻿Если бы у меня было восемь часов на то, чтобы срубить дерево, я потратил бы шесть часов на то, чтобы наточить топор.",
                            Gender = 1,
                            Height = 188,
                            InterestsFlags = 49,
                            Latitude = 51.660598200000003,
                            Longitude = 39.200585799999999,
                            Name = "Chelan",
                            PartnerGender = 2,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -50L,
                            Age = (short)38,
                            CityId = 170978781L,
                            CurrentOffset = 0,
                            Description = "﻿Когда чувствуешь уныние, ищи исцеление в труде.",
                            Gender = 1,
                            Height = 189,
                            InterestsFlags = 832,
                            Latitude = 51.727035649999998,
                            Longitude = 36.192247956921115,
                            Name = "Bbyaakod",
                            PartnerGender = 3,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -51L,
                            Age = (short)17,
                            CityId = 174159235L,
                            CurrentOffset = 0,
                            Description = "﻿Лучшая работа — это высокооплачиваемое хобби.",
                            Gender = 1,
                            Height = 190,
                            InterestsFlags = 532,
                            Latitude = 53.2423778,
                            Longitude = 34.3668288,
                            Name = "Zadam",
                            PartnerGender = 1,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -52L,
                            Age = (short)17,
                            CityId = 172497247L,
                            CurrentOffset = 0,
                            Description = "﻿Если никто не знает, что именно вы делаете, никто не знает, что вы делаете это не так.",
                            Gender = 1,
                            Height = 191,
                            InterestsFlags = 2068,
                            Latitude = 53.193783600000003,
                            Longitude = 45.006741250609664,
                            Name = "Bine",
                            PartnerGender = 2,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -53L,
                            Age = (short)27,
                            CityId = 177211127L,
                            CurrentOffset = 0,
                            Description = "﻿Он делал непонятно что, но делал это отлично.",
                            Gender = 1,
                            Height = 192,
                            InterestsFlags = 7,
                            Latitude = 56.860517450000003,
                            Longitude = 53.197730742455306,
                            Name = "﻿dinosaur",
                            PartnerGender = 3,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -54L,
                            Age = (short)33,
                            CityId = 179737040L,
                            CurrentOffset = 0,
                            Description = "﻿Мужчины взрослеют к шестидесяти годам, женщины — примерно к пятнадцати.",
                            Gender = 1,
                            Height = 193,
                            InterestsFlags = 104,
                            Latitude = 53.198627000000002,
                            Longitude = 50.113987000000002,
                            Name = "Coolfire ПяткаСлона",
                            PartnerGender = 1,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -55L,
                            Age = (short)17,
                            CityId = 174706474L,
                            CurrentOffset = 0,
                            Description = "﻿Слишком многие у нас живут не работая; и почти столько же — работают не живя.",
                            Gender = 1,
                            Height = 194,
                            InterestsFlags = 2084,
                            Latitude = 55.750541200000001,
                            Longitude = 37.617478200000001,
                            Name = "﻿expensive ▌Г ▌р ▌У ▌с ▌Т ▌ь ▌",
                            PartnerGender = 2,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -56L,
                            Age = (short)26,
                            CityId = 170978781L,
                            CurrentOffset = 0,
                            Description = "﻿Минимум желаемого — это максимум возможного.",
                            Gender = 2,
                            Height = 195,
                            InterestsFlags = 2368,
                            Latitude = 51.727035649999998,
                            Longitude = 36.192247956921115,
                            Name = "Мария",
                            PartnerGender = 1,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -57L,
                            Age = (short)30,
                            CityId = 174159235L,
                            CurrentOffset = 0,
                            Description = "Ты не перестаешь искать силы и уверенность вовне, а искать следует в себе. Они там всегда и были.",
                            Gender = 2,
                            Height = 196,
                            InterestsFlags = 81,
                            Latitude = 53.2423778,
                            Longitude = 34.3668288,
                            Name = "Анна",
                            PartnerGender = 1,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -58L,
                            Age = (short)16,
                            CityId = 172497247L,
                            CurrentOffset = 0,
                            Description = "﻿Люди редко знают, чего хотят, пока не получат того, чего требуют.",
                            Gender = 2,
                            Height = 197,
                            InterestsFlags = 1288,
                            Latitude = 53.193783600000003,
                            Longitude = 45.006741250609664,
                            Name = "Диана",
                            PartnerGender = 2,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -59L,
                            Age = (short)16,
                            CityId = 177211127L,
                            CurrentOffset = 0,
                            Description = "﻿Один важный секрет: нужно идти туда, куда хочется, а не туда, куда якобы надо.",
                            Gender = 2,
                            Height = 198,
                            InterestsFlags = 1041,
                            Latitude = 56.860517450000003,
                            Longitude = 53.197730742455306,
                            Name = "Алисия",
                            PartnerGender = 3,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -60L,
                            Age = (short)24,
                            CityId = 179737040L,
                            CurrentOffset = 0,
                            Description = "﻿Чаще всего хорошей мечтой является та, в которую очень сложно поверить.",
                            Gender = 2,
                            Height = 199,
                            InterestsFlags = 704,
                            Latitude = 53.198627000000002,
                            Longitude = 50.113987000000002,
                            Name = "Амелия",
                            PartnerGender = 1,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -61L,
                            Age = (short)35,
                            CityId = 174706474L,
                            CurrentOffset = 0,
                            Description = "﻿Несбыточные желания называют «благими». Как видно, считается, что осуществимы лишь неблагие желания.",
                            Gender = 2,
                            Height = 200,
                            InterestsFlags = 322,
                            Latitude = 55.750541200000001,
                            Longitude = 37.617478200000001,
                            Name = "Елизавета",
                            PartnerGender = 2,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -62L,
                            Age = (short)17,
                            CityId = 150993485L,
                            CurrentOffset = 0,
                            Description = "﻿То, чего хочется, всегда кажется необходимым.",
                            Gender = 2,
                            Height = 201,
                            InterestsFlags = 560,
                            Latitude = 59.938732000000002,
                            Longitude = 30.316229,
                            Name = "﻿BlossomBreeze",
                            PartnerGender = 3,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -63L,
                            Age = (short)22,
                            CityId = 171488446L,
                            CurrentOffset = 0,
                            Description = "﻿Обидно, когда твои мечты сбываются у других!",
                            Gender = 2,
                            Height = 202,
                            InterestsFlags = 800,
                            Latitude = 50.5955595,
                            Longitude = 36.587339399999998,
                            Name = "Ditha",
                            PartnerGender = 1,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -64L,
                            Age = (short)33,
                            CityId = 171488446L,
                            CurrentOffset = 0,
                            Description = "﻿Удвоенное желание есть страсть, удвоенная страсть становится безумием.",
                            Gender = 2,
                            Height = 203,
                            InterestsFlags = 322,
                            Latitude = 50.5955595,
                            Longitude = 36.587339399999998,
                            Name = "﻿EnchantingEmber",
                            PartnerGender = 2,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        },
                        new
                        {
                            Id = -65L,
                            Age = (short)17,
                            CityId = 172182020L,
                            CurrentOffset = 0,
                            Description = "﻿Ничто так не разочаровывает, как исполнение наших желаний.",
                            Gender = 2,
                            Height = 204,
                            InterestsFlags = 2068,
                            Latitude = 51.660598200000003,
                            Longitude = 39.200585799999999,
                            Name = "﻿LunaFae",
                            PartnerGender = 3,
                            SearchOffset = 0,
                            State = 0,
                            TemporaryInterestsFlags = 0
                        });
                });

            modelBuilder.Entity("YourMatchTgBot.Models.UserMedia", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaFileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "MediaFileId");

                    b.ToTable("UserMedia");

                    b.HasData(
                        new
                        {
                            UserId = -1L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/1.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -2L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/6.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -3L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/7.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -4L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/10.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -5L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/15.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -6L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/21.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -7L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/22.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -8L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/23.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -9L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/24.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -10L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/25.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -11L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/28.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -12L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/29.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -13L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/30.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -14L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/31.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -15L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/32.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -16L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/33.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -17L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/35.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -18L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/36.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -19L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/40.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -20L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/41.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -21L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/44.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -22L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/45.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -23L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/47.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -24L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/49.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -25L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/50.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -26L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/54.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -27L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/55.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -28L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/default.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -29L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/default.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -30L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/default.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -31L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/default.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -32L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/default.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -33L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/default.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -34L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/default.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -35L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/default.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -36L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/default.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -37L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/default.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -38L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/default.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -39L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/default.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -40L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/default.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -41L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/default.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -42L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/default.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -43L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/default.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -44L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/default.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -45L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/default.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -46L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/default.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -47L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/default.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -48L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/default.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -49L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/default.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -50L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/default.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -51L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/default.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -52L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/default.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -53L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/default.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -54L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/default.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -55L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/default.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -56L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/1.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -57L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/2.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -58L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/3.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -59L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/4.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -60L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/5.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -61L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/8.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -62L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/9.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -63L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/15.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -64L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/21.png",
                            MediaType = 2
                        },
                        new
                        {
                            UserId = -65L,
                            MediaFileId = "https://api.slingacademy.com/public/sample-users/22.png",
                            MediaType = 2
                        });
                });

            modelBuilder.Entity("InterestUser", b =>
                {
                    b.HasOne("YourMatchTgBot.Models.Interest", null)
                        .WithMany()
                        .HasForeignKey("InterestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YourMatchTgBot.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YourMatchTgBot.Models.TempInterest", b =>
                {
                    b.HasOne("YourMatchTgBot.Models.Interest", "Interest")
                        .WithMany()
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YourMatchTgBot.Models.User", "User")
                        .WithMany("TemporaryInterests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YourMatchTgBot.Models.TempUserMedia", b =>
                {
                    b.HasOne("YourMatchTgBot.Models.User", null)
                        .WithMany("TemporaryPhotos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YourMatchTgBot.Models.User", b =>
                {
                    b.HasOne("YourMatchTgBot.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.Navigation("City");
                });

            modelBuilder.Entity("YourMatchTgBot.Models.UserMedia", b =>
                {
                    b.HasOne("YourMatchTgBot.Models.User", null)
                        .WithMany("Photos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YourMatchTgBot.Models.User", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("TemporaryInterests");

                    b.Navigation("TemporaryPhotos");
                });
#pragma warning restore 612, 618
        }
    }
}
