//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourMatchTgBot.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Program {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Program() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("YourMatchTgBot.Resources.Program", typeof(Program).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string WaitingName {
            get {
                return ResourceManager.GetString("WaitingName", resourceCulture);
            }
        }
        
        internal static string WaitingAge {
            get {
                return ResourceManager.GetString("WaitingAge", resourceCulture);
            }
        }
        
        internal static string dd {
            get {
                return ResourceManager.GetString("dd", resourceCulture);
            }
        }
        
        internal static string MM {
            get {
                return ResourceManager.GetString("MM", resourceCulture);
            }
        }
        
        internal static string yyyy {
            get {
                return ResourceManager.GetString("yyyy", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Man {
            get {
                return ResourceManager.GetString("Man", resourceCulture);
            }
        }
        
        internal static string Women {
            get {
                return ResourceManager.GetString("Women", resourceCulture);
            }
        }
        
        internal static string WaitingGender {
            get {
                return ResourceManager.GetString("WaitingGender", resourceCulture);
            }
        }
        
        internal static string WaitingInterests {
            get {
                return ResourceManager.GetString("WaitingInterests", resourceCulture);
            }
        }
        
        internal static string WaitingHeight {
            get {
                return ResourceManager.GetString("WaitingHeight", resourceCulture);
            }
        }
        
        internal static string WaitingLocation {
            get {
                return ResourceManager.GetString("WaitingLocation", resourceCulture);
            }
        }
        
        internal static string GetPhotosFromProfile {
            get {
                return ResourceManager.GetString("GetPhotosFromProfile", resourceCulture);
            }
        }
        
        internal static string WaitingPhotos {
            get {
                return ResourceManager.GetString("WaitingPhotos", resourceCulture);
            }
        }
        
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        internal static string GetProfileDescription {
            get {
                return ResourceManager.GetString("GetProfileDescription", resourceCulture);
            }
        }
        
        internal static string WaitingDescription {
            get {
                return ResourceManager.GetString("WaitingDescription", resourceCulture);
            }
        }
        
        internal static string ReadyProfile {
            get {
                return ResourceManager.GetString("ReadyProfile", resourceCulture);
            }
        }
        
        internal static string FillProfileAgain {
            get {
                return ResourceManager.GetString("FillProfileAgain", resourceCulture);
            }
        }
        
        internal static string WaitingPartnerGender {
            get {
                return ResourceManager.GetString("WaitingPartnerGender", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string CorrectCity {
            get {
                return ResourceManager.GetString("CorrectCity", resourceCulture);
            }
        }
        
        internal static string Error_LongName {
            get {
                return ResourceManager.GetString("Error_LongName", resourceCulture);
            }
        }
        
        internal static string Error_LongDescription {
            get {
                return ResourceManager.GetString("Error_LongDescription", resourceCulture);
            }
        }
        
        internal static string Error_TooYoung {
            get {
                return ResourceManager.GetString("Error_TooYoung", resourceCulture);
            }
        }
        
        internal static string Error_IncorrectAge {
            get {
                return ResourceManager.GetString("Error_IncorrectAge", resourceCulture);
            }
        }
        
        internal static string Error_IncorrectVariant {
            get {
                return ResourceManager.GetString("Error_IncorrectVariant", resourceCulture);
            }
        }
        
        internal static string LeaveCurrent {
            get {
                return ResourceManager.GetString("LeaveCurrent", resourceCulture);
            }
        }
    }
}
